# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: adlancel <adlancel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/09 17:31:41 by adlancel          #+#    #+#              #
#    Updated: 2022/01/11 15:06:31 by adlancel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = a.out 

SRCS = Animal_class.cpp Cat_class.cpp Dog_class.cpp WrongAnimal_class.cpp WrongCat_class.cpp Brain_class.cpp main.cpp

HEADER = Animal_class.hpp Cat_class.hpp Dog_class.hpp WrongAnimal_class.hpp WrongCat_class.hpp Brain_class.hpp

CC = clang++

CFLAGS = -Wextra -Werror -Wall -std=c++98

OBJS = ${SRCS:.cpp=.o}

.c.o: 
			@${CC} ${CFLAGS} ${HEADER} -c $< -o ${<:.cpp=.o}

all:		${NAME}

${NAME}:	${OBJS}
			@${CC} ${CFLAGS} ${OBJS} -o ${NAME}
			
clean:		
			@rm -rf ${OBJS}

fclean:		clean
			@rm -rf ${NAME}

re:			fclean all

.PHONY: all clean fclean re

